-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 21:34:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `apellidos` VARCHAR(255) NULL,
  `domicilio` VARCHAR(255) NULL,
  `telefono` VARCHAR(19) NULL,
  `estatus` TINYINT NULL,
  PRIMARY KEY (`id_usuarios`),
  UNIQUE INDEX `id_usuarios_UNIQUE` (`id_usuarios` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(255) NULL,
  `stock` INT NULL,
  `imagen` VARCHAR(255) NULL,
  `precio_unitario` FLOAT NULL,
  `costo_unitario` FLOAT NULL,
  `provedor` VARCHAR(255) NULL,
  `impuestos` FLOAT NULL,
  PRIMARY KEY (`id_productos`),
  UNIQUE INDEX `id_productos_UNIQUE` (`id_productos` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `usuario_id` INT NULL,
  `cantidad` INT NULL,
  `importe` FLOAT NULL,
  PRIMARY KEY (`id_ventas`),
  UNIQUE INDEX `id_ventas_UNIQUE` (`id_ventas` ASC) VISIBLE,
  INDEX `fk_ventas_usuarios_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_ventas_productos1_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id_usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_productos1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`productos` (`id_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
